### ISSUE TITLE
hack: give agent optional bordom timeout that +1s the max procs?

### ISSUE THREAD

**Issue by Aricg** [fafrd/aquarium#2]
Bordom is part of agency .. right?

for example if agent throws something into the background with some simple job control `foo &`
it could, via bordom timer be given +1 to max procs...

Or perhaps an interactive element, where the output screen shows the current # of procs and the user can increase this value:

also the split output screen is neat, I could envision sending this data to gpt4 with a prefixed with a general explanation prompt and see if it could come up with good ideas to escape the loop.
 
cool project.

edit: 7 dollars?!
This thing is pretty dangerous... I think that feeding the last 10 or 20 lines of stdout would be almost as effective,
and cost a lot less.

**Comment by Aricg** [comment]
also apt is too verbose and i need to prompt to run apt with -qq
perhaps add -qq in the same way you hacked -y

**Comment by fafrd** [comment]
I like the idea of a timer- let's track that issue in https://github.com/fafrd/aquarium/issues/3

also, I'm making another issue to track the cost, I agree it can be pricy and probably done in a better way. https://github.com/fafrd/aquarium/issues/6

**Comment by fafrd** [comment]
Set -qq on apt-get https://github.com/fafrd/aquarium/commit/1f7b9d7def9a6b4c6020759c8fa24a02c100781a
