### ISSUE TITLE
Actor gets blocked

### ISSUE THREAD

**Issue by eracle** [fafrd/aquarium#3]
Running:
`OPENAI_API_KEY="..." ./aquarium --goal "Your goal is to check for any security vulnerabilities."`

Running the following command and gets stuck:
`sudo apt-get install -q -y rkhunter`

![blocked](https://user-images.githubusercontent.com/3613943/227806245-d533b548-232a-476e-aa79-e2950184aa8e.png)

It would be nice to have a timeout that can fire if the terminal's content doesn't change in x seconds. In case of fire triggering the loop of getting the terminal's output back to the AI.

**Comment by fafrd** [comment]
I like the timeout idea- I'll work on implementing this.

However specifically for `apt-get install rkhunter`, I was able to work around it by running `sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y rkhunter`.

Making a quick change to set `DEBIAN_FRONTEND=noninteractive` for all commands...

**Comment by fafrd** [comment]
Workaround: I have set DEBIAN_FRONTEND=noninteractive for all shells: https://github.com/fafrd/aquarium/commit/3f2482b1e3e5db64fcce0e17e00b0850e8920a07

requires the container to be rebuilt: `docker build -t aquarium .`
