### ISSUE TITLE
Slice bounds out of range - seems like a one-off error.

### ISSUE THREAD

**Issue by ttulttul** [fafrd/aquarium#5]
panic: runtime error: slice bounds out of range [721:720]

goroutine 82 [running]:
aquarium/actor.(*Actor).iteration(0xc000096000)
	/Users/ksimpson/git/aquarium/actor/actor.go:299 +0xf6a
aquarium/actor.(*Actor).Loop.func2()
	/Users/ksimpson/git/aquarium/actor/actor.go:141 +0x68
created by aquarium/actor.(*Actor).Loop
	/Users/ksimpson/git/aquarium/actor/actor.go:134 +0x97b

**Comment by ttulttul** [comment]
I'm putting in some debugging to see what's going on here.

**Comment by fafrd** [comment]
Can you give the exact command that produces this outcome?

**Comment by ttulttul** [comment]
I think it was this one:

Develop a Slack plugin using the Slack Python API that sends everything users write into the channel #gpt to OpenAI's ChatGPT API. The Python Slack API can be installed using pip install slack-sdk. When you use apt to install packages, use -qq to make the output silent except for errors.

**Comment by ttulttul** [comment]
But it does not always happen, for some reason. I have noticed that there are glitchy characters in the debug.log, suggesting some corruption in terminal response handling.

**Comment by fafrd** [comment]
Ah I understand why this is occuring. The reason we see some garbage/glitchy bytes in the stream is because I am not de-multiplexing the stdout/stderr stream from Docker.

explanation: https://stackoverflow.com/questions/46478169/explain-and-remove-useless-bytes-at-the-start-of-docker-exec-response

working on a fix...
